### ISSUE TITLE
The device used in your reported results

### ISSUE THREAD

**Issue by pierre-zhao** [stevezheng23/xlnet_extension_tf#86]
Hi, steve,

Can you show me your GPU device (memory, number of GPU) for your QuAC results?  
I got some OOM errors for reimplementing your code >_>.
ThX!

**Comment by stevezheng23** [comment]
Hi @pierre-zhao , I didn't log the exact device setting for my QuAC experiments, but the following setting should work,
For XLNet-base, you can try 4 x 32GB GPU with per-GPU batch size = 12;
For XLNet-large, you can try 8 x 32GB GPU with per-GPU batch size = 6;

**Comment by pierre-zhao** [comment]
Hi @stevezheng23 ，thanks a lot.

**Comment by pierre-zhao** [comment]
Sorry about another question.
--BATCHSIZE--  in run_quac.sh is the total batch size for all GPUs or per-GPU batch size?

**Comment by pierre-zhao** [comment]
I think (maybe wrong) --**BATCHSIZE**-- is per-GPU batch size.
And in the multi-GPU setting, --**num_core_per_host**-- should be set to the number of GPUs?

**Comment by stevezheng23** [comment]
In the run_quac.sh script, `--batchsize` is per-gpu batch size, `--numgpus` is num of gpus

**Comment by pierre-zhao** [comment]
Thank u very much for your help！！
I would like to ask you the last question: can you briefly talk about the augmentations used in your QuAC experiment.

**Comment by pierre-zhao** [comment]
Can you release your QuAC model? 
I have followed your setting in README.md, but still fail to achieve the results 71.5(F1 score).
